# Generated by Django 3.2.6 on 2021-11-22 02:00

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='broke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Battry', models.BooleanField()),
                ('Mic', models.BooleanField()),
                ('Speaker', models.BooleanField()),
                ('Lcd', models.BooleanField()),
                ('Touch', models.BooleanField()),
                ('FrontCam', models.BooleanField()),
                ('BackCam', models.BooleanField()),
                ('other', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='changed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Battry', models.BooleanField()),
                ('Mic', models.BooleanField()),
                ('Speaker', models.BooleanField()),
                ('Lcd', models.BooleanField()),
                ('Touch', models.BooleanField()),
                ('FrontCam', models.BooleanField()),
                ('BackCam', models.BooleanField()),
                ('other', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=5)),
                ('ram', models.CharField(max_length=5)),
                ('BattryHealth', models.CharField(max_length=2)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('Broken', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.broke')),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.changed')),
                ('color', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.color')),
                ('image', models.ManyToManyField(related_name='products', to='myapi.Image')),
                ('mod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapi.mod')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
